project:
  type: website

website:
  title: "Ateliers codons"
  site-url: "https://ateliers-codons.netlify.app"
  navbar:
    right:
      - icon: github
        href: https://github.com/codons-blog/
      - icon: twitter
        href: https://twitter.com/AteliersCodons/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

